// ============================================
// NEXT.JS PROJECT EXPORT UTILITY
// ============================================
// Handles ZIP creation and download for full-stack Next.js projects

import JSZip from 'jszip';
import type { WebsiteArtifact } from '@/types/database';

/**
 * Generate a project README with setup instructions
 */
export function generateProjectReadme(artifact: WebsiteArtifact): string {
  const projectName = artifact.metadata?.patterns ? 'Next.js Application' : 'My App';
  const envVars = artifact.metadata?.envVars?.required || [];

  return `# ${projectName}

Generated with [Anything Platform](https://anything.com)

## Quick Start

### 1. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 2. Set Up Environment Variables

Copy \`.env.example\` to \`.env.local\` and fill in the values:

\`\`\`bash
cp .env.example .env.local
\`\`\`

Required variables:
${envVars.map(v => `- \`${v}\``).join('\n')}

### 3. Set Up Database (if applicable)

If your project includes Supabase migrations:

1. Create a [Supabase](https://supabase.com) project
2. Go to the SQL Editor
3. Copy and paste each migration from \`supabase/migrations/\` in order
4. Execute the migrations

### 4. Run Development Server

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Structure

\`\`\`
src/
├── app/              # Next.js App Router pages
├── components/       # Reusable React components
├── lib/             # Utilities and services
├── hooks/           # Custom React hooks
├── types/           # TypeScript type definitions
└── styles/          # Global styles

supabase/
└── migrations/      # Database migration scripts

public/             # Static assets
package.json        # Project dependencies
.env.example        # Environment variables template
\`\`\`

## Available Scripts

- \`npm run dev\` - Start development server
- \`npm run build\` - Build for production
- \`npm run start\` - Run production server
- \`npm run lint\` - Run ESLint

## Features

${artifact.metadata?.patterns ? artifact.metadata.patterns.map(p => `- ${p.replace(/-/g, ' ')}`).join('\n') : '- Full-stack application with multiple features'}

## Deployment

### Vercel (Recommended)

1. Push to GitHub
2. Connect repository to [Vercel](https://vercel.com)
3. Set environment variables
4. Deploy

### Other Platforms

- **Netlify**: Use \`npm run build\` as build command
- **Railway**: Deploy from GitHub
- **DigitalOcean**: Use App Platform

## Environment Variables

See \`.env.example\` for all available configuration options.

## Troubleshooting

### Port Already in Use
\`\`\`bash
# Use a different port
npm run dev -- -p 3001
\`\`\`

### Database Connection Issues
- Verify Supabase credentials in \`.env.local\`
- Check that migrations have been applied
- Ensure RLS policies are correctly configured

### Build Errors
- Delete \`node_modules\` and \`.next\` folders
- Run \`npm install\` again
- Clear npm cache: \`npm cache clean --force\`

## Learning Resources

- [Next.js Documentation](https://nextjs.org/docs)
- [Supabase Documentation](https://supabase.com/docs)
- [TypeScript Handbook](https://www.typescriptlang.org/docs/)
- [Tailwind CSS](https://tailwindcss.com/docs)

## Support

For issues or questions, check the documentation of the relevant tool:
- Next.js: nextjs.org
- Supabase: supabase.com
- Tailwind: tailwindcss.com

---

Generated by Anything Platform
`;
}

/**
 * Generate .env.example file
 */
export function generateEnvExample(artifact: WebsiteArtifact): string {
  const required = artifact.metadata?.envVars?.required || [];
  const optional = artifact.metadata?.envVars?.optional || [];

  let content = '# Environment Variables\n\n';

  if (required.length > 0) {
    content += '# REQUIRED - Must be set for the application to work\n';
    required.forEach(varName => {
      const description = getEnvVarDescription(varName);
      content += `${varName}=${description}\n`;
    });
    content += '\n';
  }

  if (optional.length > 0) {
    content += '# OPTIONAL - These have default values\n';
    optional.forEach(varName => {
      const description = getEnvVarDescription(varName);
      content += `# ${varName}=${description}\n`;
    });
    content += '\n';
  }

  return content;
}

/**
 * Get description for common environment variables
 */
function getEnvVarDescription(varName: string): string {
  const descriptions: Record<string, string> = {
    NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co',
    NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your_supabase_anonymous_key',
    SUPABASE_SERVICE_ROLE_KEY: 'your_supabase_service_role_key',
    NEXT_PUBLIC_APP_URL: 'http://localhost:3000',
    DATABASE_URL: 'postgresql://user:password@localhost:5432/dbname',
    API_KEY: 'your_api_key_here',
    SECRET_KEY: 'your_secret_key_here',
  };

  return descriptions[varName] || 'your_value_here';
}

/**
 * Create a ZIP file with all project files
 */
export async function createProjectZip(artifact: WebsiteArtifact, projectName: string): Promise<Blob> {
  const zip = new JSZip();

  // Add all generated files
  artifact.files.forEach(file => {
    const path = file.path.startsWith('/') ? file.path.slice(1) : file.path;
    zip.file(path, file.content);
  });

  // Ensure README exists
  if (!artifact.files.some(f => f.path === '/README.md')) {
    zip.file('README.md', generateProjectReadme(artifact));
  }

  // Ensure .env.example exists
  if (!artifact.files.some(f => f.path === '/.env.example')) {
    zip.file('.env.example', generateEnvExample(artifact));
  }

  // Create .gitignore if it doesn't exist
  if (!artifact.files.some(f => f.path === '/.gitignore')) {
    zip.file(
      '.gitignore',
      `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Production
.next/
out/
dist/

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
Thumbs.db
`
    );
  }

  return zip.generateAsync({ type: 'blob' });
}

/**
 * Download project as ZIP file
 */
export async function downloadProjectZip(artifact: WebsiteArtifact, projectName: string): Promise<void> {
  try {
    const blob = await createProjectZip(artifact, projectName);
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectName.toLowerCase().replace(/\s+/g, '-')}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to create ZIP:', error);
    throw new Error('Failed to create project ZIP file');
  }
}

/**
 * Get file count and statistics
 */
export function getProjectStats(artifact: WebsiteArtifact): {
  totalFiles: number;
  byType: Record<string, number>;
  totalSize: number;
} {
  const byType: Record<string, number> = {};
  let totalSize = 0;

  artifact.files.forEach(file => {
    const type = file.type || 'unknown';
    byType[type] = (byType[type] || 0) + 1;
    totalSize += file.content.length;
  });

  return {
    totalFiles: artifact.files.length,
    byType,
    totalSize,
  };
}

/**
 * Format file size for display
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes';

  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
}
